spring.application.name=backend

# ===
# PostgreSQL
# ====

spring.datasource.url=jdbc:postgresql://localhost:5432/finchat_db

spring.datasource.username=postgres

spring.datasource.password=Caleb2491

spring.datasource.driver-class-name=org.postgresql.Driver

# ===
# Hibernate
# ===

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# Server
# ==========================================

server.port=8080
spring.application.name=backend

jwt.secret=FinChatSuperSecretKey2026SpringBootJWTAuthenticationSecureKey12345

jwt.expiration=86400000